[package]
name = "tool"
version = "0.1.0"
edition = "2021"

[dependencies]
proconio = { version = "0.5.0", features = ["derive"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
clap = { version = "4.5.9", features = ["derive"] }
itertools = "0.13.0"